version: '3.8'

services:
  nginx:
    container_name: kok-nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - kok-network

networks:
  kok-network:
    driver: bridge
