version: '3.8'

services:
  kok-dev:
    container_name: kok-dev
    image: ${DOCKERHUB_USERNAME}/kok-dev:${KOK_DEV_TAG}
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - kok-network

  # Redis 설정
  redis:
    image: redis:7.0
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kok-network

volumes:
  redis_data:

networks:
  kok-network:
    driver: bridge
