name: kok-dev-CD (Deploy to Dev)

on:
  push:
    branches:
      - develop
      - deploy/dev_cd # 배포 테스트 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Latest Docker Image Tag
        id: latest_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/kok-dev/tags" | jq -r '.results[0].name')
          cd ${{ secrets.COMPOSE_FILE_PATH }}
          sed -i '/^KOK_DEV_TAG=/d' .env
          echo "KOK_DEV_TAG = ${{ env.LATEST_TAG }}" >> .env


      - name: Create SSH key file
        run: echo "${{ secrets.NCP_KEY }}" > /tmp/NCP_KEY.pem

      - name: Set permissions for SSH key file
        run: chmod 400 /tmp/NCP_KEY.pem

      - name: Upload `docker-compose.yml` to NCP
        run: |
          scp -i /tmp/NCP_KEY.pem -o StrictHostKeyChecking=no infra/docker-compose-dev.yml ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }}:${{ secrets.COMPOSE_FILE_PATH }}

      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.NCP_KEY }}
          script: |
            cd ${{ secrets.COMPOSE_FILE_PATH }}
            
            echo "KOK_DEV_TAG=${{ env.LATEST_TAG }}" > .env
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose -f docker-compose-dev.yml up -d
